name: Build images for Docker Hub
on:
  push:
    branches:
    - master
  schedule:
    - cron: '0 12 * * MON'  # Run every Monday
env:
  DEFAULT_VERSION: 'v3.3.0'
  DEFAULT_SERVER: 'apache'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['v3.3.0']
        server: ['apache', 'nginx']
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Log in to Docker Hub
      run: docker login
           -u "${{ secrets.dockerhub_user }}"
           -p "${{ secrets.dockerhub_token }}"

    - name: Build ${{ matrix.version }}-${{ matrix.server }}
      run: make VERSIONS=${{ matrix.version }} SERVERS=${{ matrix.server }}

    # As we build multiple versions now, we need one to be the default
    - name: Set default tag for ${{ matrix.version }}-${{ matrix.server }}
      if: matrix.server == env.DEFAULT_SERVER && matrix.version == env.DEFAULT_VERSION
      run: docker tag owasp/modsecurity-crs:${{ matrix.version }}-${{ matrix.server }}
                      owasp/modsecurity-crs:${{ matrix.server }}

    - name: Push ${{ matrix.version }}-${{ matrix.server }}
      run: docker push --all-tags owasp/modsecurity-crs

