name: Build images for Docker Hub
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
        - 3.3-apache
        - 3.3-nginx
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Log in to Docker Hub
      run: docker login
           -u ${{ secrets.dockerhub_user }}
           -p ${{ secrets.dockerhub_token }}

    - name: Build ${{ matrix.image }}
      run: docker build ${{ matrix.image }}
           --tag owasp/modsecurity-crs:${{ matrix.image }}
           --tag owasp/modsecurity-crs:$(echo ${{ matrix.image }} | sed 's/-.*//')
           --tag owasp/modsecurity-crs:$(echo ${{ matrix.image }} | sed 's/.*-//')

    - name: Push ${{ matrix.image }}
      run: docker push owasp/modsecurity-crs
